#!/usr/bin/env bash

notify () {
	local message="$1"
	shift
	for destination in "$@"; do
		case "$destination" in
			stdout)    echo "$(date) | $message" & ;;
			syslog)    logger -i greeny "$message" & ;;
			telegram)  telegram-send "$message" & ;;
			*)         echo "Unknown destination: $destination" ;;
		esac
	done
}

shutdown () {
	notify "$message_stop" "${notification_startstop[@]}"
	exit
}

gpioconf () {
	notify "$message_gpiosetup" "@{notification_system[@]}"
	local zone
	for zone in "${zones[@]}"; do
		local lightrelay="$zone"_lightrelay
		local waterlevel="$zone"_waterlevel
		echo "${!waterlevel}" > /sys/class/gpio/export
		echo "${!lightrelay}" > /sys/class/gpio/export
	done
	notify "$message_done" "@{notification_system[@]}"
}

. greeny.conf

trap "shutdown" SIGINT
notify "$message_start" "${notification_startstop[@]}"

while true; do
	for zone in "${zones[@]}"; do
	
		lightrelay="$zone"_lightrelay
		waterlevel="$zone"_waterlevel
		lightup="$zone"_lightup
		lightdown="$zone"_lightdown
		
		case $(cat /sys/class/gpio/${!waterlevel}/value) in
			0)  [ -f /var/run/greeny-water-alert ]   && rm -rf /var/run/greeny-water-alert && notify "$zone: $message_waternormal" "${notification_waterlevel[@]}" ;;
			1)  [ ! -f /var/run/greeny-water-alert ] && touch /var/run/greeny-water-alert  && notify "$zone: $message_waterlow"    "${notification_waterlevel[@]}" ;;
		esac
		
		case $(date +%H) in
			"${!lightup}")   [ $(cat /sys/class/gpio/gpio${!lightrelay}/value) = 0 ] && echo 1 > /sys/class/gpio/gpio"${!lightrelay}"/value && notify "$zone: $message_lightup"   "${notification_lightswitch[@]}" ;;
			"${!lightdown}") [ $(cat /sys/class/gpio/gpio${!lightrelay}/value) = 1 ] && echo 0 > /sys/class/gpio/gpio"${!lightrelay}"/value && notify "$zone: $message_lightdown" "${notification_lightswitch[@]}" ;;
		esac
		
	done
	sleep "$pollingtime"
done
