#!/usr/bin/env bash

notify () {
	local message="$1"
	shift
	for destination in "$@"; do
		case "$destination" in
			stdout)    echo "$(date) | $message" & ;;
			syslog)    logger -i greeny "$message" & ;;
			telegram)  telegram-send "$message" & ;;
			*)         echo "Unknown destination: $destination" ;;
		esac
	done
}

shutdown () {
	notify "$message_stop" "${notification_startstop[@]}"
	exit
}

. greeny.conf

trap "shutdown" SIGINT
notify "$message_start" "${notification_startstop[@]}"

while true; do
	for zone in "${zones[@]}"; do
		lightrelay="$zone"_lightrelay
		waterlevel="$zone"_waterlevel
		
		case $(cat /sys/class/gpio/${!waterlevel}/value) in
			0)  [ -f /var/run/greeny-water-alert ] && rm -rf /var/run/greeny-water-alert && notify "$zone: $message_waternormal" "${notification_waterlevel[@]}" ;;
			1)  [ ! -f /var/run/greeny-water-alert ] && touch /var/run/greeny-water-alert && notify "$zone: $message_waterlow" "${notification_waterlevel[@]}" ;;
		esac
	done
	sleep 1
done
